/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Code2 extends javax.swing.JFrame {

    /**
     * Creates new form Code2
     */
    public Code2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Code2");
        setLocation(new java.awt.Point(380, 200));
        setMinimumSize(new java.awt.Dimension(606, 368));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 26, 600, 220);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Form Of Your Message.");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(115, 0, 370, 28);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transform.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 243, 160, 98);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton2PropertyChange(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 243, 161, 98);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Code.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String message;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String text=jTextArea1.getText();
int length = text.length();
int a=0;
String s="";
while(a<length)
{
char z=text.charAt(a);

switch(z)
{
    case 'a':
    s=s+"q";
    break;
    
    case 'b':
    s=s+"w";
    break;
    
    case 'c':
    s=s+"e";
    break;
    
    case 'd':
    s=s+"r";
    break;
    
    case 'e':
    s=s+"t";
    break;
    
    case 'f':
    s=s+"y";
    break;
    
    case 'g':
    s=s+"u";
    break;
    
    case 'h':
    s=s+"i";
    break;
    
    case 'i':
    s=s+"o";
    break;
    
    case 'j':
    s=s+"p";
    break;
    
    case 'k':
    s=s+"a";
    break;
    
    case 'l':
    s=s+"s";
    break;
    
    case 'm':
    s=s+"d";
    break;
    
    case 'n':
    s=s+"f";
    break;
    
    case 'o':
    s=s+"g";
    break;
    
    case 'p':
    s=s+"h";
    break;
    
    case 'q':
    s=s+"j";
    break;
    
    case 'r':
    s=s+"k";
    break;
    
    case 's':
    s=s+"l";
    break;
    
    case 't':
    s=s+"z";
    break;
    
    case 'u':
    s=s+"x";
    break;
    
    case 'v':
    s=s+"c";
    break;
    
    case 'w':
    s=s+"v";
    break;
    
    case 'x':
    s=s+"b";
    break;
    
    case 'y':
    s=s+"n";
    break;
    
    case 'z':
    s=s+"m";
    break;
    
    case 'A':
    s=s+"Q";
    break;
    
    case 'B':
    s=s+"W";
    break;
    
    case 'C':
    s=s+"E";
    break;
    
    case 'D':
    s=s+"R";
    break;
    
    case 'E':
    s=s+"T";
    break;
    
    case 'F':
    s=s+"Y";
    break;
    
    case 'G':
    s=s+"U";
    break;
    
    case 'H':
    s=s+"I";
    break;
    
    case 'I':
    s=s+"O";
    break;
    
    case 'J':
    s=s+"P";
    break;
    
    case 'K':
    s=s+"A";
    break;
    
    case 'L':
    s=s+"S";
    break;
    
    case 'M':
    s=s+"D";
    break;
    
    case 'N':
    s=s+"F";
    break;
    
    case 'O':
    s=s+"G";
    break;
    
    case 'P':
    s=s+"H";
    break;
    
    case 'Q':
    s=s+"J";
    break;
    
    case 'R':
    s=s+"K";
    break;
    
    case 'S':
    s=s+"L";
    break;
    
    case 'T':
    s=s+"Z";
    break;
    
    case 'U':
    s=s+"X";
    break;
    
    case 'V':
    s=s+"C";
    break;
    
    case 'W':
    s=s+"V";
    break;
    
    case 'X':
    s=s+"B";
    break;
    
    case 'Y':
    s=s+"N";
    break;
    
    case 'Z':
    s=s+"M";
    break;
    
    case '1':
    s=s+"7";
    break;

    case '2':
    s=s+"4";
    break;

    case '3':
    s=s+"1";
    break;

    case '4':
    s=s+"0";
    break;

    case '5':
    s=s+"8";
    break;

    case '6':
    s=s+"5";
    break;

    case '7':
    s=s+"2";
    break;

    case '8':
    s=s+"9";
    break;

    case '9':
    s=s+"6";
    break;

    case '0':
    s=s+"3";
    break;
    
    default:
    s=s+z;
}
a++;
}
jTextArea1.setText(s);

jButton2.setVisible(true);
jButton1.setVisible(false);
jButton2.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CodeApplied.message=jTextArea1.getText();
CodeApplied.code=CodeApplied.code+"2";
new CodeApplied().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton2PropertyChange
jButton2.setVisible(false);
    }//GEN-LAST:event_jButton2PropertyChange

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
jTextArea1.setText(message);
jButton1.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Code2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Code2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Code2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Code2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Code2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
