/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class Code3 extends javax.swing.JFrame {

    /**
     * Creates new form Code3
     */
    public Code3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Code3");
        setLocation(new java.awt.Point(380, 200));
        setMinimumSize(new java.awt.Dimension(606, 368));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 26, 600, 220);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Form Of Your Message.");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(115, 0, 370, 28);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Transform.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 243, 160, 98);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save1.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton2PropertyChange(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 243, 161, 98);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Code.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String message;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String text=jTextArea1.getText();
int length = text.length();
int a=0;
int n=0,m=0;
String s="";
while(a<length)
{
char z=text.charAt(a);

switch(z)
{
    case 'a':
    n=2+a;
    break;
    
    case 'b':
    n=3+a;
    break;
    
    case 'c':
    n=4+a;
    break;
    
    case 'd':
    n=5+a;
    break;
    
    case 'e':
    n=6+a;
    break;
    
    case 'f':
    n=7+a;
    break;
    
    case 'g':
    n=8+a;
    break;
    
    case 'h':
    n=9+a;
    break;
    
    case 'i':
    n=10+a;
    break;
    
    case 'j':
    n=11+a;
    break;
    
    case 'k':
    n=12+a;
    break;
    
    case 'l':
    n=13+a;
    break;
    
    case 'm':
    n=14+a;
    break;
    
    case 'n':
    n=15+a;
    break;
    
    case 'o':
    n=16+a;
    break;
    
    case 'p':
    n=17+a;
    break;
    
    case 'q':
    n=18+a;
    break;
    
    case 'r':
    n=19+a;
    break;
    
    case 's':
    n=20+a;
    break;
    
    case 't':
    n=21+a;
    break;
    
    case 'u':
    n=22+a;
    break;
    
    case 'v':
    n=23+a;
    break;
    
    case 'w':
    n=24+a;
    break;
    
    case 'x':
    n=25+a;
    break;
    
    case 'y':
    n=26+a;
    break;
    
    case 'z':
    n=27+a;
    break;
    
    case 'A':
    m=2+a;
    break;
    
    case 'B':
    m=3+a;
    break;
    
    case 'C':
    m=4+a;
    break;
    
    case 'D':
    m=5+a;
    break;
    
    case 'E':
    m=6+a;
    break;
    
    case 'F':
    m=7+a;
    break;
    
    case 'G':
    m=8+a;
    break;
    
    case 'H':
    m=9+a;
    break;
    
    case 'I':
    m=10+a;
    break;
    
    case 'J':
    m=11+a;
    break;
    
    case 'K':
    m=12+a;
    break;
    
    case 'L':
    m=13+a;
    break;
    
    case 'M':
    m=14+a;
    break;
    
    case 'N':
    m=15+a;
    break;
    
    case 'O':
    m=16+a;
    break;
    
    case 'P':
    m=17+a;
    break;
    
    case 'Q':
    m=18+a;
    break;
    
    case 'R':
    m=19+a;
    break;
    
    case 'S':
    m=20+a;
    break;
    
    case 'T':
    m=21+a;
    break;
    
    case 'U':
    m=22+a;
    break;
    
    case 'V':
    m=23+a;
    break;
    
    case 'W':
    m=24+a;
    break;
    
    case 'X':
    m=25+a;
    break;
    
    case 'Y':
    m=26+a;
    break;
    
    case 'Z':
    m=27+a;
    break;
    
    case '0':
    s=s+"1";
    break;
    
    case '1':
    s=s+"8";
    break;

    case '2':
    s=s+"5";
    break;

    case '3':
    s=s+"2";
    break;

    case '4':
    s=s+"9";
    break;

    case '5':
    s=s+"6";
    break;

    case '6':
    s=s+"7";
    break;

    case '7':
    s=s+"3";
    break;

    case '8':
    s=s+"4";
    break;

    case '9':
    s=s+"0";
    break;
    
    default:
    s=s+z;
}

while(n>26)
{n=n-26;}

while(m>26)
{m=m-26;}

switch (n)
{
    case 1:
    s=s+"a";
    break;
    
    case 2:
    s=s+"b";
    break;
    
    case 3:
    s=s+"c";
    break;
    
    case 4:
    s=s+"d";
    break;
    
    case 5:
    s=s+"e";
    break;
    
    case 6:
    s=s+"f";
    break;
    
    case 7:
    s=s+"g";
    break;
    
    case 8:
    s=s+"h";
    break;
    
    case 9:
    s=s+"i";
    break;
    
    case 10:
    s=s+"j";
    break;
    
    case 11:
    s=s+"k";
    break;
    
    case 12:
    s=s+"l";
    break;
    
    case 13:
    s=s+"m";
    break;
    
    case 14:
    s=s+"n";
    break;
    
    case 15:
    s=s+"o";
    break;
    
    case 16:
    s=s+"p";
    break;
    
    case 17:
    s=s+"q";
    break;
    
    case 18:
    s=s+"r";
    break;
    
    case 19:
    s=s+"s";
    break;
    
    case 20:
    s=s+"t";
    break;
    
    case 21:
    s=s+"u";
    break;
    
    case 22:
    s=s+"v";
    break;
    
    case 23:
    s=s+"w";
    break;
    
    case 24:
    s=s+"x";
    break;
    
    case 25:
    s=s+"y";
    break;
    
    case 26:
    s=s+"z";
    break;
}

switch (m)
{
    case 1:
    s=s+"A";
    break;
    
    case 2:
    s=s+"B";
    break;
    
    case 3:
    s=s+"C";
    break;
    
    case 4:
    s=s+"D";
    break;
    
    case 5:
    s=s+"E";
    break;
    
    case 6:
    s=s+"F";
    break;
    
    case 7:
    s=s+"G";
    break;
    
    case 8:
    s=s+"H";
    break;
    
    case 9:
    s=s+"I";
    break;
    
    case 10:
    s=s+"J";
    break;
    
    case 11:
    s=s+"K";
    break;
    
    case 12:
    s=s+"L";
    break;
    
    case 13:
    s=s+"M";
    break;
    
    case 14:
    s=s+"N";
    break;
    
    case 15:
    s=s+"O";
    break;
    
    case 16:
    s=s+"P";
    break;
    
    case 17:
    s=s+"Q";
    break;
    
    case 18:
    s=s+"R";
    break;
    
    case 19:
    s=s+"S";
    break;
    
    case 20:
    s=s+"T";
    break;
    
    case 21:
    s=s+"U";
    break;
    
    case 22:
    s=s+"V";
    break;
    
    case 23:
    s=s+"W";
    break;
    
    case 24:
    s=s+"X";
    break;
    
    case 25:
    s=s+"Y";
    break;
    
    case 26:
    s=s+"Z";
    break;
}
n=0;
m=0;

a++;
}
jTextArea1.setText(s);

jButton2.setVisible(true);
jButton1.setVisible(false);
jButton2.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CodeApplied.message=jTextArea1.getText();
CodeApplied.code=CodeApplied.code+"3";
new CodeApplied().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton2PropertyChange
jButton2.setVisible(false);
    }//GEN-LAST:event_jButton2PropertyChange

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
jTextArea1.setText(message);
jButton1.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Code3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Code3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Code3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Code3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Code3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
