
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class CodeResult extends javax.swing.JFrame {

    /**
     * Creates new form CodeResult
     */
    public CodeResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CodeResult");
        setLocation(new java.awt.Point(360, 170));
        setMinimumSize(new java.awt.Dimension(646, 429));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 26, 640, 220);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 281, 660, 34);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 323, 192, 32);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(563, 363, 77, 37);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Secret Message");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(198, 0, 239, 28);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codes Applied To Your Message");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(116, 255, 368, 28);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Assigned Pin To Your Secret Message");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 325, 435, 28);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Note : Remember Codes-Applied & Assigned-Pin.");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 375, 512, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CodeResult.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String secret;
public static String code;
String title;
String account;
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
if(jTextField1.getText().equals(""))
{        try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String check="select AssignedPin from secretmessages";
            ResultSet rst = stmt.executeQuery(check);
            rst.last();
            if(rst.getRow()==0)
            {
            jTextField1.setText("SM-0001");
            }
            else
            {
            String AssignedPin = rst.getString("AssignedPin");
            String s="";
            int n=3;
            
              while(n<7)
              {
              char c=AssignedPin.charAt(n);
              s=s+c;
              n++;
              }
              int Assignedpin=Integer.parseInt(s);
              Assignedpin++;
              String pin=Assignedpin+"";
              int l=pin.length();
       switch (l) {
           case 1:
               jTextField1.setText("SM-000"+pin);
               break;
           case 2:
               jTextField1.setText("SM-00"+pin);
               break;
           case 3:
               jTextField1.setText("SM-0"+pin);
               break;
           case 4:
               jTextField1.setText("SM-"+pin);
               break;
       }
              
              

            }
            
        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
jTextArea1.setText(secret);
jTextArea2.setText(code);
jButton1.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int responce=JOptionPane.showConfirmDialog(this,"Have You Noted CODES-APPLIED & ASSIGNED-PIN?");
if(responce==0)
{
    String s= JOptionPane.showInputDialog(this,"Enter A Title To Recognize This Secret Message.\nAnd Note It For Decoding Message. (Not More Than 20 Alphabets)").trim();
    while(s.length()>20||s.equals(""))
    {
    if(s.length()>20)
       JOptionPane.showMessageDialog(this,"Title Should Not Exceed 20 Alphabets.");
    if(s.equals(""))
       JOptionPane.showMessageDialog(this,"Title Cannot Be Null.");
    
    s= JOptionPane.showInputDialog(this,"Enter A Title To Recognize This Secret Message.\nAnd Note It For Decoding Message. (Not More Than 20 Alphabets)").trim();
    }
    account=JOptionPane.showInputDialog(this,"Enter The Username Of Person Who Can Decode This Secret Message.\nIf You Don't Know Who Will Decode, Don't Enter Anything Just Press 'Ok' Button.").trim();
    
        title=s;
        String pin=jTextField1.getText();
        try {Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/secretmessaging","root","manager");
        Statement stmt=con.createStatement();
        String save="insert into secretmessages values('"+pin+"','"+title+"','"+secret+"','"+code+"','"+account+"')"; 
        int check=stmt.executeUpdate(save);
        JOptionPane.showMessageDialog(this,check+" SECRET MESSAGE Saved Sucessfully.");
        con.close();
        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
        }
        new Login().setVisible(true);
        this.dispose();
    }

else if(responce==1)
{JOptionPane.showMessageDialog(this,"Plsz. Note Down CODES-APPLIED & ASSIGNED-PIN.\nIt Is Necessary For Decoding This Message.");}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
