
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class DecodeCheck extends javax.swing.JFrame {

    /**
     * Creates new form DecodeCheck
     */
    public DecodeCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DecodeCheck");
        setLocation(new java.awt.Point(380, 169));
        setMinimumSize(new java.awt.Dimension(606, 431));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Verifying User For Decoding");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 602, 49);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Secret Message");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(102, 49, 396, 49);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Assigned Pin To");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 120, 398, 42);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Secret Message");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(15, 160, 367, 42);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel6.setText("SM-");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 141, 67, 42);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Codes Applied To Message");
        jLabel7.setOpaque(true);
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 223, 575, 42);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User Is Verified.");
        jLabel8.setOpaque(true);
        jLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel8PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 331, 490, 69);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(495, 139, 107, 46);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField2PropertyChange(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(0, 263, 602, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Decode1.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 300, 100, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 314, 200, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DecodeCheck.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 401);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String account="";
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
String AssignedPin="SM-"+jTextField1.getText();
jButton2.setVisible(false);
jTextField1.setBorder(null);
jTextField1.setEditable(false);

        try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String check="select * from secretmessages where AssignedPin='"+AssignedPin+"'";
            ResultSet rst = stmt.executeQuery(check);
            rst.last();
            if(rst.getRow()==0)
            {JOptionPane.showMessageDialog(this,"Secret Message Not Found.");
                new Login().setVisible(true);
                this.dispose();}
            else
            {
            if(rst.getString("Account").equalsIgnoreCase(account)||rst.getString("Account").equals(""))
              {
               jTextField1.setEditable(false);
               jLabel7.setVisible(true);
               jTextField2.setVisible(true);
               jTextField2.requestFocus();
              }
            else
              {JOptionPane.showMessageDialog(this,"Sorry, You Are Not Allowed To\nDecode This Secret Message.");
                new Login().setVisible(true);
                this.dispose();}
            }
            con.close();
        } catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
jLabel7.setVisible(false);
    }//GEN-LAST:event_jLabel7PropertyChange

    private void jLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel8PropertyChange
jLabel8.setVisible(false);
    }//GEN-LAST:event_jLabel8PropertyChange

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Decode.pin="SM-"+jTextField1.getText();

new Decode().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField2PropertyChange
        jTextField2.setVisible(false);
    }//GEN-LAST:event_jTextField2PropertyChange

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String AssignedPin="SM-"+jTextField1.getText().trim();
        String CodesApplied=jTextField2.getText().trim();
        int x=3;
        String z="s";
        jTextField2.setEditable(false);
        jTextField2.setVisible(true);

        try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String check="select * from secretmessages where AssignedPin='"+AssignedPin+"'";
            ResultSet rst = stmt.executeQuery(check);
            rst.last();
            if(rst.getString("CodesApplied").equals(CodesApplied))
            {while(x>0)
                {
                    if(x==1)
                    {z="";}

                    if(JOptionPane.showInputDialog("Enter Title Given To Secret Message.\n("+x+" Chance"+z+" Left.)").trim().equalsIgnoreCase(rst.getString("Title")))
                    {
                        jLabel8.setVisible(true);
                        jButton1.setVisible(true);
                        jButton1.requestFocus();
                        break;
                    }
                    x--;
                    if(x==0)
                    {
                        JOptionPane.showMessageDialog(this,"Entered Titles Were Wrong.");
                        new Login().setVisible(true);
                        this.dispose();
                    }
                }
            }
            else
            {JOptionPane.showMessageDialog(this,"Entered Codes-Applied Were Incorrect.");
                new Login().setVisible(true);
                this.dispose();}

        } catch (Exception e) {JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
String a=jTextField1.getText(),s="";
int n=0;

if(a.equals(""))
{}
else
{
int x = a.length();
char c=a.charAt(x-1);
int z = (int)c;

if(x>4)
{
  while(n<4)
  {c=a.charAt(n);
  s=s+c;
  n++;}
  jTextField1.setText(s);
  n=0;
  s="";
  a=jTextField1.getText();
  x = a.length();
  c=a.charAt(x-1);
  z = (int)c;
}

if(47<z&&z<58)
{}
else
{if(x==1)
{jTextField1.setText("");}
else
{while(47>z||z>58)
{  while(n<x-1)
  {c=a.charAt(n);
  s=s+c;
  n++;}
  jTextField1.setText(s);
  
  if(jTextField1.getText().length()==0)
  break;
  
  n=0;
  s="";
  a=jTextField1.getText();
  x = a.length();
  c=a.charAt(x-1);
  z = (int)c;
}
}
}
}
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
String a=jTextField2.getText(),s="";
int n=0;

if(a.equals(""))
{}
else
{
int x = a.length();
char c=a.charAt(x-1);
int z = (int)c;

if(x>19)
{
  while(n<19)
  {c=a.charAt(n);
  s=s+c;
  n++;}
  jTextField2.setText(s);
  n=0;
  s="";
  a=jTextField2.getText();
  x = a.length();
  c=a.charAt(x-1);
  z = (int)c;
}

if(48<z&&z<54)
{}
else
{if(x==1)
{jTextField2.setText("");}
else
{while(48>z||z>54)
{ while(n<x-1)
  {c=a.charAt(n);
  s=s+c;
  n++;}
  jTextField2.setText(s);
  
  if(jTextField2.getText().length()==0)
  break;
  
  n=0;
  s="";
  a=jTextField2.getText();
  x = a.length();
  c=a.charAt(x-1);
  z = (int)c;
}
}
}
}
    }//GEN-LAST:event_jTextField2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecodeCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecodeCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecodeCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecodeCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecodeCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
