
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ForgotPassword");
        setLocation(new java.awt.Point(352, 208));
        setMinimumSize(new java.awt.Dimension(663, 381));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jComboBox1.setMaximumRowCount(1);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(145, 55, 50, 25);

        jComboBox2.setMaximumRowCount(1);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(190, 55, 50, 25);

        jComboBox3.setMaximumRowCount(1);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(235, 55, 50, 25);

        jComboBox4.setMaximumRowCount(1);
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(280, 55, 50, 25);

        jComboBox5.setMaximumRowCount(1);
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(325, 55, 50, 25);

        jComboBox6.setMaximumRowCount(1);
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(370, 55, 50, 25);

        jComboBox7.setMaximumRowCount(1);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(415, 55, 50, 25);

        jComboBox8.setMaximumRowCount(1);
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "3", "4", "5", "6", "7", "8", "9" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(460, 55, 50, 25);

        jComboBox9.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 15)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was the house number and street name you lived in as a child?", "What were the last four digits of your childhood telephone number?", "What primary school did you attend?", "In what town or city was your first full time job?", "In what town or city did you meet your spouse/partner?", "What is the middle name of your oldest child?", "What are the last five digits of your driver's licence number?", "What is your grandmother's (on your mother's side) maiden name?", "What is your spouse or partner's mother's maiden name?", "In what town or city did your mother and father meet?", "What time of the day were you born? (hh:mm)", "What time of the day was your first child born? (hh:mm)" }));
        jComboBox9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox9FocusLost(evt);
            }
        });
        jComboBox9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox9PropertyChange(evt);
            }
        });
        jComboBox9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox9KeyTyped(evt);
            }
        });
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(0, 190, 655, 27);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(353, 110, 200, 34);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField2PropertyChange(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 213, 255, 34);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Alpha-Numeric Code");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(166, 0, 316, 45);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(135, 45, 385, 45);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Your Username");
        jLabel4.setOpaque(true);
        jLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel4PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 110, 255, 34);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Your Selected Question And Its Answer");
        jLabel5.setOpaque(true);
        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 164, 533, 28);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Enter New Password");
        jLabel6.setOpaque(true);
        jLabel6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel6PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 279, 265, 28);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   Confirm Password");
        jLabel7.setOpaque(true);
        jLabel7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel7PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 322, 265, 28);

        jPasswordField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPasswordField1PropertyChange(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(263, 279, 200, 28);

        jPasswordField2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 20)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPasswordField2PropertyChange(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(263, 322, 200, 28);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChangeYourPassword.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 279, 99, 71);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Return.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(455, 263, 200, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ForgotPassword.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 657, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
jComboBox2.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
jComboBox3.requestFocus();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
jComboBox4.requestFocus();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
jComboBox5.requestFocus();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
jComboBox6.requestFocus();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
jComboBox7.requestFocus();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
jComboBox8.requestFocus();
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
String code=(String) jComboBox1.getSelectedItem()+jComboBox2.getSelectedItem()+jComboBox3.getSelectedItem()+jComboBox4.getSelectedItem()+jComboBox5.getSelectedItem()+jComboBox6.getSelectedItem()+jComboBox7.getSelectedItem()+jComboBox8.getSelectedItem();
if(code.equals("SUSHIL17"))
{
jLabel4.setVisible(true);
jTextField1.setVisible(true);
    
jLabel2.setText("Entered Alpha-Numeric Code");
jLabel2.setSize(343,45);
jLabel2.setLocation(156,0);
jComboBox1.removeAllItems();
jComboBox2.removeAllItems();
jComboBox3.removeAllItems();
jComboBox4.removeAllItems();
jComboBox5.removeAllItems();
jComboBox6.removeAllItems();
jComboBox7.removeAllItems();
jComboBox8.removeAllItems();
jComboBox1.addItem("S");
jComboBox2.addItem("U");
jComboBox3.addItem("S");
jComboBox4.addItem("H");
jComboBox5.addItem("I");
jComboBox6.addItem("L");
jComboBox7.addItem("1");
jComboBox8.addItem("7");
jButton2.setVisible(false);
jTextField1.requestFocus();
}
else
{JOptionPane.showMessageDialog(this,"Wrong PIN Entered.");
new Login().setVisible(true);
this.dispose();}
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jComboBox1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
jLabel5.setVisible(false);
    }//GEN-LAST:event_jLabel5PropertyChange

    private void jComboBox9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox9PropertyChange
jComboBox9.setVisible(false);
    }//GEN-LAST:event_jComboBox9PropertyChange

    private void jTextField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField2PropertyChange
jTextField2.setVisible(false);
    }//GEN-LAST:event_jTextField2PropertyChange

    private void jComboBox9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox9FocusLost

    }//GEN-LAST:event_jComboBox9FocusLost

    private void jLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel4PropertyChange
jLabel4.setVisible(false);
    }//GEN-LAST:event_jLabel4PropertyChange

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
jTextField1.setVisible(false);
    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String username=jTextField1.getText();
        try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String check="select * from accounts where Username='"+username+"'";
            ResultSet rst = stmt.executeQuery(check);
            rst.last();
            if(rst.getRow()==0)
            {JOptionPane.showMessageDialog(this,"Account Not Found.");
                new Login().setVisible(true);
                this.dispose();}
            else
            {
                jLabel5.setVisible(true);
                jComboBox9.setVisible(true);
                jTextField2.setVisible(true);
                jComboBox9.requestFocus();
                jTextField1.setEditable(false);
                jTextField1.setVisible(true);
            }
        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox9KeyTyped
jTextField2.requestFocus();
    }//GEN-LAST:event_jComboBox9KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
String username=jTextField1.getText();
String question=(String) jComboBox9.getSelectedItem();
String answer=jTextField2.getText();

        try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String check="select * from accounts where Username='"+username+"'";
            ResultSet rst = stmt.executeQuery(check);
            rst.last();
            
            if(rst.getString("SecurityQuestion").equals(question)&&rst.getString("Answer").equalsIgnoreCase(answer))
            {
             jLabel6.setVisible(true);
             jLabel7.setVisible(true);
             jPasswordField1.setVisible(true);
             jPasswordField2.setVisible(true);
             jButton1.setVisible(true);
             
             jTextField2.setEditable(false);
             jTextField2.setVisible(true);
             jPasswordField1.requestFocus();
             jComboBox9.removeAllItems();
             jComboBox9.addItem(question);
            }
            else
            {
             JOptionPane.showMessageDialog(this,"Selected Question OR Given Answer Is Wrong.");
             new Login().setVisible(true);
             this.dispose();
            }
            
        } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel6PropertyChange
jLabel6.setVisible(false);
    }//GEN-LAST:event_jLabel6PropertyChange

    private void jLabel7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel7PropertyChange
jLabel7.setVisible(false);
    }//GEN-LAST:event_jLabel7PropertyChange

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String username=jTextField1.getText().trim();
String password=new String(jPasswordField1.getPassword()).trim();
String password1=new String(jPasswordField2.getPassword()).trim();

if(password.equals(password1))
{int responce=JOptionPane.showConfirmDialog(this,"Confirm Change Account's Password?");
     if(responce==0)
     {    try {Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/SecretMessaging", "root", "manager");
            Statement stmt=con.createStatement();
            String change="update accounts set Password='"+password+"' where Username='"+username+"'";
            int check=stmt.executeUpdate(change);
            con.close();
            JOptionPane.showMessageDialog(this,check+" Account's Password Changed Sucessfully.");
            
    } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
     new Login().setVisible(true);
             this.dispose();
}
else
{JOptionPane.showMessageDialog(this,"Passwords Does Not Match In Both Cases.");
jPasswordField1.setText(null);
jPasswordField2.setText(null);}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPasswordField2PropertyChange
jPasswordField1.setVisible(false);
    }//GEN-LAST:event_jPasswordField2PropertyChange

    private void jPasswordField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPasswordField1PropertyChange
jPasswordField2.setVisible(false);
    }//GEN-LAST:event_jPasswordField1PropertyChange

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
jButton1.requestFocus();
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
jPasswordField2.requestFocus();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introdujLabel2Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
